# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e1a9670d81261795674de0ea08fd9018"
name = "thank-you-and-order-status"
handle = "thank-you-and-order-status"
application_url = "https://tip-spyware-savings-remaining.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://tip-spyware-savings-remaining.trycloudflare.com/auth/callback",
  "https://tip-spyware-savings-remaining.trycloudflare.com/auth/shopify/callback",
  "https://tip-spyware-savings-remaining.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
